interface BLESagaAction {
    BLE_CONNECT_SAGA_ACTION : string,
    BLE_DISCONNECT_SAGA_ACTION: string,
    BLE_READ_SAGA_ACTION: string,
    BLE_WRITE_SAGA_ACTION: string
}

export const BLE_SAGA_ACTION: BLESagaAction = {
    BLE_CONNECT_SAGA_ACTION : "BLE_CONNECT_SAGA_ACTION",
    BLE_DISCONNECT_SAGA_ACTION: "BLE_DISCONNECT_SAGA_ACTION",
    BLE_READ_SAGA_ACTION: "BLE_READ_SAGA_ACTION",
    BLE_WRITE_SAGA_ACTION: "BLE_WRITE_SAGA_ACTION"
}

interface BLEReducerAction {
    BLE_STATE_UPDATE_REDUCER_ACTION : string;
}

export const BLE_REDUCER_ACTION: BLEReducerAction = {
    BLE_STATE_UPDATE_REDUCER_ACTION : "BLE_STATE_UPDATE_REDUCER_ACTION"
}